#!/bin/ksh

username=$USER
jobname="nclDtsmp.cluma2"
iaM=0
nmx=90

for vid in {0..4} #{0..14}   #BIG LOOP
do

jobname="nclDtsmp_"$iaM"_"$vid
cat > $jobname << end_pbscommands_cluma2
#!/bin/bash
#################################################
# PBS commands
#################################################
#PBS -N $jobname
#PBS -l cput=1:00:00
#PBS -l nodes=1:ppn=1
#PBS -k oe
#PBS -j oe
#PBS -u $username
#################################################
end_pbscommands_cluma2

cat >> $jobname << ncljob
cd $HOME/dart-terrsysmp/analysis
ncl plot_ensemble_ts.ncl ind_aM=$iaM var_id=$vid nmax=$nmx
ncljob

chmod u+x $jobname
qsub $jobname
done
exit 0 
